### ISSUE TITLE
DbAndroid Network (IP address) mode fails to work

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2917]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3033
Originally created at: Sat Feb 13 10:29:15 2016
Originally last updated at: Sat Feb 13 10:29:15 2016

OS: Windows Server 2008 SP2
IDE: Android Studio 1.5.1
Android API: 19
APP: nRF Temp 2.0 for BLE

code added to APP project: libs/SQLiteStudioRemote.jar  from DbAndroid 1.1.0
	protected void onCreate(final Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
.................................
		SQLiteStudioService.instance().start(this);
       }

	protected void onDestroy() {
		SQLiteStudioService.instance().stop();
                super.onDestroy();
.................................
        }

Problem: USB cable - port forwarding mode works well with the following URL:  
android://0123456789ABCDEF:@:12121/com.nordic.android.nrftemp/sensors.db

Network (IP address) mode failed for the URL:
android://:@192.168.0.100:12121/com.nordic.android.nrftemp/sensors.db

with the SQLiteStudio message:  Cannot connect to device , because it''s not visible to your computer.

Network (IP address) mode failed for the URL:
android://:@192.168.0.100:12121/!/sensors.db
crash with exception:

02-12 20:33:07.236 9289-9577/com.nordic.android.nrftemp D/SQLiteStudioRemote: New client from 192.168.0.80
02-12 20:33:07.246 9289-9577/com.nordic.android.nrftemp W/SQLiteStudioRemote: Client initialization successful.
02-12 20:33:07.476 9289-9577/com.nordic.android.nrftemp W/dalvikvm: threadid=13: thread exiting with uncaught exception (group=0x41608bf0)
02-12 20:33:07.476 9289-9577/com.nordic.android.nrftemp E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
                                                                          Process: com.nordic.android.nrftemp, PID: 9289
                                                                          android.database.sqlite.SQLiteException: Can''t downgrade database from version 3 to 1
                                                                              at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
                                                                              at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
                                                                              at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                              at pl.com.salsoft.sqlitestudioremote.internal.SQLiteStudioDbService.getDb(SQLiteStudioDbService.java:114)
                                                                              at pl.com.salsoft.sqlitestudioremote.internal.SQLiteStudioDbService.exec(SQLiteStudioDbService.java:63)
                                                                              at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.execAndRespond(ClientHandler.java:310)
                                                                              at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.handleRequest(ClientHandler.java:239)
                                                                              at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.readClientChannel(ClientHandler.java:182)
                                                                              at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.run(ClientHandler.java:129)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:861)
02-12 20:33:08.377 9289-9289/com.nordic.android.nrftemp D/SQLiteStudioRemote: Shutting down SQLiteStudioService instance.
\n\n**Operating system:**\nWindows (other)\n\n**Version:**\n3.0.7

**Comment by pawelsalawa** [comment]
Originally created at: Sat Feb 13 10:29:15 2016

it fails when USB cable unpluged, only when USB cable connected, the Network (IP address) mode works wiht the following URL:
android://0123456789ABCDEF:@192.168.0.100:12121/com.nordic.android.nrftemp/sensors.db

in this situation, it seems the connection to the Android APP sqlite db is built via USB cable, not via IP network,

**Comment by pawelsalawa** [comment]
Originally created at: Sat Feb 13 10:29:15 2016

Network (IP address) mode works when USB cable connected and using the following URL:
android://0123456789ABCDEF:@192.168.0.100:12121/com.nordic.android.nrftemp/sensors.db
but it seems the connection from SQLiteStudio to SQLiteStudioRemote service is built via the USB cable instead of IP network.

**Comment by pawelsalawa** [comment]
Originally created at: Sat Feb 13 10:29:15 2016

_Status changed to **assigned**_

**Comment by pawelsalawa** [comment]
Originally created at: Sat Feb 13 10:29:15 2016

I was unable to reproduce this, but I made some tweaks to the plugin anyway, so I think it's best to give another shot with the plugin when the new version is released (either on May or June).

**Comment by pawelsalawa** [comment]
Originally created at: Sat Feb 13 10:29:15 2016

_Status changed to **rejected**_

**Rejection reason:**
Cannot reproduce.
