### ISSUE TITLE
SQLiteException: Can''t downgrade database from version xx to 1

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#2976]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3092
Originally created at: Mon Jun 13 10:00:55 2016
Originally last updated at: Mon Jun 13 10:00:55 2016

When I try to use the DbAndroid plugin with the jar file, I cannot connect to my app. Whenever I try to establish the connection, the app crashes with the following stacktrace:

android.database.sqlite.SQLiteException: Can''t downgrade database from version 43 to 1
	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at pl.com.salsoft.sqlitestudioremote.internal.SQLiteStudioDbService.getDb(SQLiteStudioDbService.java:114)
	at pl.com.salsoft.sqlitestudioremote.internal.SQLiteStudioDbService.exec(SQLiteStudioDbService.java:63)
	at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.execAndRespond(ClientHandler.java:277)
	at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.handleRequest(ClientHandler.java:232)
	at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.readClientChannel(ClientHandler.java:180)
	at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.run(ClientHandler.java:127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

This is caused by the usage of SQLiteOpenHelper, which is a tool that can be used when an app needs automatic upgrades to a database. 
If the app has a version higher than 1, this crash will occur (because the SQLiteOpenHelper thinks it sees a database with a higher version than it was configured for).

I have written a patch that does not use the SQLiteOpenHelper to open the database and therefore does not show this behaviour. With this patch, everything works fine for me.\n\n**Operating system:**\nWindows 8.1\n\n**Version:**\n3.1.0

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

unfortunately, there is no way to upload files, so I will post the patch in plain text here:

Index: SQLiteStudioDbOpenHelper.java
===================================================================
--- SQLiteStudioDbOpenHelper.java	(revision 2)
+++ SQLiteStudioDbOpenHelper.java	(working copy)
@@ -2,21 +2,23 @@
 
 import android.content.Context;
 import android.database.sqlite.SQLiteDatabase;
-import android.database.sqlite.SQLiteOpenHelper;
 
 /\\*\\*
  \\* Created by SalSoft Pawel Salawa on 08.02.15.
  \\*/
-public class SQLiteStudioDbOpenHelper extends SQLiteOpenHelper {
-    public SQLiteStudioDbOpenHelper(Context context, String dbPath) {
-        super(context, dbPath, null, 1);
-    }
+public class SQLiteStudioDbOpenHelper {
+	private final Context context;
+	private final String dbPath;
+	private SQLiteDatabase database;
 
-    @Override
-    public void onCreate(SQLiteDatabase db) {
-    }
+	public SQLiteStudioDbOpenHelper(Context context, String dbPath) {
+		this.context = context;
+		this.dbPath = dbPath;
+	}
 
-    @Override
-    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
-    }
+	public SQLiteDatabase getWritableDatabase() {
+		if (database == null)
+			database = context.openOrCreateDatabase(dbPath, 0, null, null);
+		return database;
+	}
 }

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

Here is it again, this time with complete paths:

Index: SQLiteStudioRemoteProject/sqlitestudioremote/src/main/java/pl/com/salsoft/sqlitestudioremote/internal/SQLiteStudioDbOpenHelper.java
===================================================================
--- SQLiteStudioRemoteProject/sqlitestudioremote/src/main/java/pl/com/salsoft/sqlitestudioremote/internal/SQLiteStudioDbOpenHelper.java	(revision 2)
+++ SQLiteStudioRemoteProject/sqlitestudioremote/src/main/java/pl/com/salsoft/sqlitestudioremote/internal/SQLiteStudioDbOpenHelper.java	(working copy)
@@ -2,21 +2,23 @@
 
 import android.content.Context;
 import android.database.sqlite.SQLiteDatabase;
-import android.database.sqlite.SQLiteOpenHelper;
 
 /\\*\\*
  \\* Created by SalSoft Pawel Salawa on 08.02.15.
  \\*/
-public class SQLiteStudioDbOpenHelper extends SQLiteOpenHelper {
-    public SQLiteStudioDbOpenHelper(Context context, String dbPath) {
-        super(context, dbPath, null, 1);
-    }
+public class SQLiteStudioDbOpenHelper {
+	private final Context context;
+	private final String dbPath;
+	private SQLiteDatabase database;
 
-    @Override
-    public void onCreate(SQLiteDatabase db) {
-    }
+	public SQLiteStudioDbOpenHelper(Context context, String dbPath) {
+		this.context = context;
+		this.dbPath = dbPath;
+	}
 
-    @Override
-    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
-    }
+	public SQLiteDatabase getWritableDatabase() {
+		if (database == null)
+			database = context.openOrCreateDatabase(dbPath, 0, null, null);
+		return database;
+	}
 }

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

Excellent, thanks! I will apply patch for 3.1.1.

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

_Status changed to **assigned**_

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

_Status changed to **done**_

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

When will be released the new version with this patch?

I have the same problem with my app.

Thanks!

**Comment by pawelsalawa** [comment]
Originally created at: Mon Jun 13 10:00:55 2016

No precise release date has been set yet, but it should be in around a month.
