### ISSUE TITLE
DbAndroid plugin &quot;downgrade&quot; problem

### ISSUE THREAD

**Issue by pawelsalawa** [pawelsalawa/sqlitestudio#3009]
_(This issue was migrated from the old bug tracker of SQLiteStudio)_

Original ID from old bug tracker: 3126
Originally created at: Wed Jul 20 14:58:08 2016
Originally last updated at: Wed Jul 20 14:58:08 2016

07-18 23:09:02.989 16857-21136/pl.modus.dmx E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-5
                                                              Process: pl.modus.dmx, PID: 16857
                                                              android.database.sqlite.SQLiteException: Can''t downgrade database from version 4 to 1
                                                                  at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
                                                                  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
                                                                  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                                                                  at pl.com.salsoft.sqlitestudioremote.internal.SQLiteStudioDbService.getDb(SQLiteStudioDbService.java:114)
                                                                  at pl.com.salsoft.sqlitestudioremote.internal.SQLiteStudioDbService.exec(SQLiteStudioDbService.java:63)
                                                                  at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.execAndRespond(ClientHandler.java:277)
                                                                  at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.handleRequest(ClientHandler.java:232)
                                                                  at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.readClientChannel(ClientHandler.java:180)
                                                                  at pl.com.salsoft.sqlitestudioremote.internal.ClientHandler.run(ClientHandler.java:127)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                  at java.lang.Thread.run(Thread.java:841)\n\n**Operating system:**\nWindows 7\n\n**Version:**\n3.1.0

**Comment by pawelsalawa** [comment]
Originally created at: Wed Jul 20 14:58:08 2016

_Status changed to **assigned**_

**Comment by pawelsalawa** [comment]
Originally created at: Wed Jul 20 14:58:08 2016

_Status changed to **done**_
